### ISSUE TITLE
Links in `info_url` are 404ing

### ISSUE THREAD

**Issue by henare** [43South/KingboroughCouncil#1] opened 2015-09-14 21:36 UTC
They're missing a space. Compare the scraped one:

```
http://kingborough.tas.gov.au/webdata/resources/files/DA-2015-267 12-09.pdf
```

with a working URL:

```
http://kingborough.tas.gov.au/webdata/resources/files/DA-2015-267  12-09.pdf
```

**Comment by 43South** [comment] 2015-09-15 00:20
Thanks for picking that up, Henare, I should have checked. Weird as I just grab the href value without altering it. I shall investigate and fix.

**Comment by 43South** [comment] 2015-09-15 01:31
I've tested the URLs in the data table. As far as I can see, it's only the first one [DA-2015-267](http://kingborough.tas.gov.au/webdata/resources/files/DA-2015-267  12-09.pdf) that's failing. The issue is that as soon as a DA closes for representations it's pulled from the list on the website and the pdf is also removed. Short of caching off copies of the pdf files I'm not sure what else to do about this. I'm having a conversation with the Council staff about how DAs are put up publicly, so in the longer-term a permanent link might be possible.

I'll close this for now as 'will not fix', but am happy for it to be reopened if there's a better solution.

**Closed as completed by 43South** 2015-09-15 01:31 UTC
